# Generated by Django 2.2.4 on 2019-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191216_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bits_id',
            field=models.CharField(default='0000P', max_length=15, unique=True),
        ),
    ]
