# Generated by Django 2.2.4 on 2019-12-18 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_profile_bits_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied_orgs',
            field=models.ManyToManyField(blank=True, default=None, related_name='applied_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_orgs',
            field=models.ManyToManyField(blank=True, default=None, related_name='member_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
