# Generated by Django 2.2.4 on 2019-12-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20191218_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualifier',
            field=models.IntegerField(default=0),
        ),
    ]
