# Generated by Django 2.2.4 on 2019-12-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Junior Member', max_length=20)),
                ('joined_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
                ('member', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('type', models.CharField(choices=[('CLUB', 'Club'), ('DEPARTMENT', 'Department'), ('DEPT_ASSOC', 'Departmental Association'), ('CULT_ASSOC', 'Cultural Association')], default=0, max_length=30)),
                ('about', models.TextField(default=' ', max_length=100)),
                ('logo', models.ImageField(default='bits.jpg', upload_to='logos')),
                ('applicants', models.ManyToManyField(blank=True, related_name='org_applics', to=settings.AUTH_USER_MODEL)),
                ('coord', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='org_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
