# Generated by Django 2.2.4 on 2019-12-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLUB', 'Club'), ('DEPARTMENT', 'Department'), ('DEPT_ASSOC', 'Departmental Association'), ('CULT_ASSOC', 'Cultural Association')], default=0, max_length=30)),
                ('interests', models.CharField(default='leisure', max_length=20)),
            ],
        ),
    ]
