# Generated by Django 2.2.4 on 2019-12-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='SearchForm',
        ),
    ]
